version: '3.8'

services:
  # The Laravel Application (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html # Mount the code for development
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db # Connect to the 'db' service
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=user
      - DB_PASSWORD=password

  # The Nginx Web Server
  nginx:
    image: nginx:1.25-alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf # Mount the config
    depends_on:
      - app

  # The MySQL Database (Optional)
  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - ./docker-data/db:/var/lib/mysql